In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import duckdb as duckdb
from IPython.display import display

In [2]:
path = ("/home/adamson/Documents/Semicolon/Data Science/data_analysis/data_and_resources/InstaCart Dataset/")
aisles = pd.read_csv(path + "aisles.csv")
departments = pd.read_csv(path + "departments.csv")
order_products = pd.read_csv(path + "order_products__prior.csv")
orders = pd.read_csv(path + "orders.csv")
products = pd.read_csv(path + "products.csv")

[display(df.head()) for df in [aisles, departments,order_products, orders, products]]

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

[None, None, None, None, None]

In [4]:
conn = duckdb.connect()

1. Join product and aisels to show product name and their aisels

In [7]:
conn.sql("""
    select product_name, aisle, 
    from products, aisles
""")

┌───────────────────────────────────────────────────────────────────────────┬────────────────────────────┐
│                               product_name                                │           aisle            │
│                                  varchar                                  │          varchar           │
├───────────────────────────────────────────────────────────────────────────┼────────────────────────────┤
│ Chocolate Sandwich Cookies                                                │ prepared soups salads      │
│ All-Seasons Salt                                                          │ prepared soups salads      │
│ Robust Golden Unsweetened Oolong Tea                                      │ prepared soups salads      │
│ Smart Ones Classic Favorites Mini Rigatoni With Vodka Cream Sauce         │ prepared soups salads      │
│ Green Chile Anytime Sauce                                                 │ prepared soups salads      │
│ Dry Nose Oil                                                              │ prepared soups salads      │
│ Pure Coconut Water With Orange                                            │ prepared soups salads      │
│ Cut Russet Potatoes Steam N' Mash                                         │ prepared soups salads      │
│ Light Strawberry Blueberry Yogurt                                         │ prepared soups salads      │
│ Sparkling Orange Juice & Prickly Pear Beverage                            │ prepared soups salads      │
│               ·                                                           │           ·                │
│               ·                                                           │           ·                │
│               ·                                                           │           ·                │
│ Madagascar Vanilla Gelato Bars                                            │ marinades meat preparation │
│ 3F Mixed Carrots Corn & Butternut Squash with Lil' Bits Purees Vegetable  │ marinades meat preparation │
│ Pomegranate Blueberry Pistachio Plus Antioxidants 1.4 oz Fruit & Nut Bars │ marinades meat preparation │
│ Vitamin C-500 mg Tablets                                                  │ marinades meat preparation │
│ Original Bagel Crisps Roasted Garlic                                      │ marinades meat preparation │
│ Baked White Cheddar Cheese Puffs                                          │ marinades meat preparation │
│ Organic Lemon Agave Ginger Super Juice                                    │ marinades meat preparation │
│ Strawberry Unsweetened Soft Drink Mix                                     │ marinades meat preparation │
│ Celery Seed                                                               │ marinades meat preparation │
│ Champagne                                                                 │ marinades meat preparation │
└───────────────────────────────────────────────────────────────────────────┴────────────────────────────┘
  ? rows (>9999 rows, 20 shown)                                                                2 columns

2. Show the total number of product in each department

3. List the name of products in the alcohol department

4. Find the average number of items per order

5. List users who have placed more than 5 orders

6. Join order_products and products to find the most frequently ordered product.

7. Find the average order_hour_of_day for each day of the week

8. List all products that have never been reordered.